version: '3.9'

services:
  code-test:
    container_name: code-test
    build:
      context: ./
      dockerfile: dev.Dockerfile

    environment:
      ENV_VARIABLE: ${ENV_VARIABLE}
      DATABASE_URL: ${DATABASE_URL}
      SECRET_KEY: ${SECRET_KEY}

    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    restart: always
    ports:
      - 3000:3000
    networks:
      - my_network

  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 1234
    ports:
      - 27017:27017

networks:
  my_network:
    external: true